export default {
	addCardBoard: "ADD_CARD_BOARD",
	addCard: "ADD_CARD",
	deleteCard: "DELETE_CARD",
	deleteCardsInList: "DELETE_CARDS_LIST",
	deleteCardsInBoard: "DELETE_CARDS_BOARD",
	deleteAssignedInCards: "DELETE_CARDS_ASSIGNED",
	reorderCard: "REORDER_CARD",
	changeTitle: "CHANGE_TITLE",
	changeDescription: "CHANGE_DESCRIPTION",
	addImage: "ADD_IMAGE",
	deleteImage: "DELETE_IMAGE",
	addFile: "ADD_FILE",
	deleteFile: "DELETE_FILE",
	renameFile: "RENAME_FILE",
	addAssigned: "ADD_ASSIGNED",
	deleteAssigned: "DELETE_ASSIGNED",
};